<?php

return [
    ['name_ar' => 'اليوم الأول', 'name_en' => 'First Day'],
    ['name_ar' => 'اليوم الثاني', 'name_en' => 'Second Day'],
    ['name_ar' => 'اليوم الثالث', 'name_en' => 'Third Day'],
    ['name_ar' => 'اليوم الرابع', 'name_en' => 'Fourth Day'],
    ['name_ar' => 'اليوم الخامس', 'name_en' => 'Fifth Day'],
    ['name_ar' => 'اليوم السادس', 'name_en' => 'Sixth Day'],
    ['name_ar' => 'اليوم السابع', 'name_en' => 'Seventh Day'],
    ['name_ar' => 'اليوم الثامن', 'name_en' => 'Eighth Day'],
    ['name_ar' => 'اليوم التاسع', 'name_en' => 'Ninth Day'],
    ['name_ar' => 'اليوم العاشر', 'name_en' => 'Tenth Day'],
    ['name_ar' => 'اليوم الحادي عشر', 'name_en' => 'Eleventh Day'],
    ['name_ar' => 'اليوم الثاني عشر', 'name_en' => 'Twelveth Day'],
    ['name_ar' => 'اليوم الثالث عشر', 'name_en' => 'Thirteenth Day'],
    ['name_ar' => 'اليوم الرابع عشر', 'name_en' => 'Fourteenth Day'],
    ['name_ar' => 'اليوم الخامس عشر', 'name_en' => 'Fifteenth Day'],
    ['name_ar' => 'اليوم السادس عشر', 'name_en' => 'Sixteen Day'],
    ['name_ar' => 'اليوم السابع عشر', 'name_en' => 'Seventeenth Day'],
    ['name_ar' => 'اليوم الثامن عشر', 'name_en' => 'Eighteen Day'],
    ['name_ar' => 'اليوم التاسع عشر', 'name_en' => 'Nineteenth Day'],
    ['name_ar' => 'اليوم العشرون', 'name_en' => 'Twentieth Day'],
    ['name_ar' => 'اليوم الحادي و العشرون', 'name_en' => 'Twenty-first Day'],
    ['name_ar' => 'اليوم الثاني و العشرون', 'name_en' => 'Twenty-Second Day'],
    ['name_ar' => 'اليوم الثالث و العشرون', 'name_en' => 'Twenty-Third Day'],
    ['name_ar' => 'اليوم الرابع و العشرون', 'name_en' => 'Twenty-Fourth Day'],
    ['name_ar' => 'اليوم الخامس و العشرون', 'name_en' => 'Twenty-Fifth Day'],
    ['name_ar' => 'اليوم السادس و العشرون', 'name_en' => 'Twenty-Sixth Day'],
    ['name_ar' => 'اليوم السابع و العشرون', 'name_en' => 'Twenty-seventh Day'],
    ['name_ar' => 'اليوم الثامن و العشرون', 'name_en' => 'Twenty-eighth Day'],
    ['name_ar' => 'اليوم التاسع و العشرون', 'name_en' => 'Twenty-ninth Day'],
    ['name_ar' => 'اليوم الثلاثون', 'name_en' => 'Thirtieth Day'],
    ['name_ar' => 'اليوم الحادي و الثلاثون', 'name_en' => 'Thirty-first Day']
];
