<?php

return [
    ['en' => ['name' => 'Kafr el-Sheikh Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Cairo Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Damietta Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Aswan Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Sohag Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'North Sinai Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Monufia Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Port Said Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Beni Suef Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Matrouh Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Qalyubia Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Suez Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Gharbia Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Alexandria Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Asyut Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'South Sinai Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Faiyum Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Giza Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Red Sea Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Beheira Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Luxor Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Minya Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Ismailia Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Dakahlia Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'New Valley Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Qena Governorate'], 'country_id'  => 1],
    ['en' => ['name' => 'Riyadh Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Makkah Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Al Madinah Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Tabuk Region'], 'country_id'  => 2],
    ['en' => ['name' => '\'Asir Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Northern Borders Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Ha\'il Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Eastern Province'], 'country_id'  => 2],
    ['en' => ['name' => 'Al Jawf Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Jizan Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Al Bahah Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Najran Region'], 'country_id'  => 2],
    ['en' => ['name' => 'Al-Qassim Region'], 'country_id'  => 2]
];
