<?php

return [
    ['name_ar' => 'محافظه كفر الشيخ','name_en' => 'Kafr el-Sheikh Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه القاهره','name_en' => 'Cairo Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه دمياط','name_en' => 'Damietta Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه اسوان','name_en' => 'Aswan Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه سوهاج','name_en' => 'Sohag Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه شمال سيناء','name_en' => 'North Sinai Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه المنوفيه','name_en' => 'Monufia Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه بورسعيد','name_en' => 'Port Said Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه بني سويف','name_en' => 'Beni Suef Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه مطروح','name_en' => 'Matrouh Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه القليوبيه','name_en' => 'Qalyubia Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه السويس','name_en' => 'Suez Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الغربيه','name_en' => 'Gharbia Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الاسكندريه','name_en' => 'Alexandria Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه اسيوط','name_en' => 'Asyut Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه جنوب سيناء','name_en' => 'South Sinai Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الفيوم','name_en' => 'Faiyum Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الجيزه','name_en' => 'Giza Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه البحر الاحمر','name_en' => 'Red Sea Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه البحيره','name_en' => 'Beheira Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الاقصر','name_en' => 'Luxor Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه المنيا','name_en' => 'Minya Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الاسماعيليه','name_en' => 'Ismailia Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الدقهليه','name_en' => 'Dakahlia Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه الوادي الجديد','name_en' => 'New Valley Governorate', 'country_id'  => 1],
    ['name_ar' => 'محافظه قنا','name_en' => 'Qena Governorate', 'country_id'  => 1],
    ['name_ar' => 'الرياض','name_en' => 'Riyadh Region', 'country_id'  => 2],
    ['name_ar' => 'مكه المكرمه','name_en' => 'Makkah Region', 'country_id'  => 2],
    ['name_ar' => 'المدينه','name_en' => 'Al Madinah Region', 'country_id'  => 2],
    ['name_ar' => 'تبوك','name_en' => 'Tabuk Region', 'country_id'  => 2],
    ['name_ar' => 'عسير','name_en' => '\'Asir Region', 'country_id'  => 2],
    ['name_ar' => 'الحدود الشماليه','name_en' => 'Northern Borders Region', 'country_id'  => 2],
    ['name_ar' => 'الحائل','name_en' => 'Ha\'il Region', 'country_id'  => 2],
    ['name_ar' => 'الشرقيه','name_en' => 'Eastern Province', 'country_id'  => 2],
    ['name_ar' => 'الجوف','name_en' => 'Al Jawf Region', 'country_id'  => 2],
    ['name_ar' => 'جازان','name_en' => 'Jizan Region', 'country_id'  => 2],
    ['name_ar' => 'الباحه','name_en' => 'Al Bahah Region', 'country_id'  => 2],
    ['name_ar' => 'نجران','name_en' => 'Najran Region', 'country_id'  => 2],
    ['name_ar' => 'القصيم','name_en' => 'Al-Qassim Region', 'country_id'  => 2]
];
